volumes:
  database-data:
    driver: local
    name: pg-aero-biker
networks:
  node-app:
    name: aero-biker-net
  global-net:
    external: true

services:
  db:
    image: postgres:16.6
    restart: always
    container_name: dev-aero-biker-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    networks:
      - node-app
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DEV_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:${VERSION}
    container_name: dev-aero-biker
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3333
      DATABASE_URL: ${DEV_DATABASE_URL}
      DB_HOST: ${DEV_DB_HOST}
      DB_NAME: ${DEV_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SALT_RESULT: ${SALT_RESULT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-app
      - global-net