name: Deploy Aero-Biker

on:
  push:
    branches:
      - feat/dev
    paths:
      - "application/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: projects-environment
    permissions:
      contents: read
      packages: write

    env:
      WORKDIR: ./application
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      
      # VPS & Docker Auth
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # App Secrets
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DEV_DB_PASSWORD:  ${{ secrets.DEV_DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version based on (SHA)
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login on GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy through SSH Pipe 
        run: |
          export IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          # Docker and VPS login
          echo "${{ env.GH_TOKEN }}" | ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker login ghcr.io -u ${{ github.actor }} --password-stdin"
          
          envsubst < ${{ env.WORKDIR }}/docker-compose.yml | ssh -i ~/.ssh/id_rsa ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
          "docker compose -p backend-aero-biker -f - up -d --no-build --remove-orphans --force-recreate"

      - name: Clean old images
        uses: snok/container-retention-policy@v3.0.1
        with:
          image-names: aero-biker
          cut-off: 5m
          keep-at-least: 2
          account: projects-univesp
          token: ${{ secrets.GITHUB_TOKEN }}